### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ms-dc** [ThiagoNelsi/dicio-api#16]
Olá Thiago, quando faço uma requisição estou tendo esse problema de CORS. Teria alguma solução para resolver este problema?

**Comment by ThiagoNelsi** [comment]
Opaa, boa noite! Como está fazendo a request? Vou tentar reproduzir o erro aqui

**Comment by ms-dc** [comment]
Estava tentando fazer a requisição por AJAX

**Comment by ms-dc** [comment]
Segue a função que estou tentando utilizar:

`function openDicionario() {

    var selectedText = window.getSelection().toString();

    if (selectedText.trim().split(' ').length > 1) {
        $.fancybox.open(document.getElementById('erroDicionario'));   
    }
    else {
        $.fancybox.open(document.getElementById('dicionario'));        

        $('.container__dicionario-title').text("Significado para: " + selectedText);

        $('.box__dicionario').empty();

        $('.box__dicionario').html('<br /><div class="loader center"></div>');

        $.ajax({
            type: "GET",
            url: "https://significado.herokuapp.com/" + selectedText,
            success: function (response) {
                var definitions = loopThrough(response[0]);
                $('.loader').hide();
                if (definitions.length > 0) {
                    definitions.forEach(fillIn);
                }
                else {
                    $('.box__dicionario').append(html);
                    var html = "<p class='box__dicionario-descricao'>Nenhum resultado encontrado";
                    $('.box__dicionario').append(html);
                }

            },
            error: function (e) {
                $('.loader').hide();
                $('.box__dicionario').append(html);
                var html = "<p class='box__dicionario-descricao'>Nenhum resultado encontrado";
                $('.box__dicionario').append(html);
            }
        });

    }    

    function loopThrough(data, timesToTry = 5) {
        var keys = Object.keys(data);
        for (var k of keys) {
            // console.log("valor",k);
            if (k === "meanings") {
                if (typeof data[k] === "object") {
                    var substantivos = Object.keys(data[k]);
                    if (substantivos.length > 0) {
                        return data[k][substantivos[0]];
                    }
                }
            }
        }
    }
    
    function fillIn(item, index) {
        var html = "<p class='box__dicionario-descricao'><strong>" + (index + 1) + "</strong>. " + item.definition + "</p><p class='box__dicionario-linha'></p >";
        $('.box__dicionario').append(html);
    }
}`

**Comment by ThiagoNelsi** [comment]
Corrigido, obrigado por reportar!

**Comment by ms-dc** [comment]
Por nada! Consegui fazer a requisição, valeu Thiago 👍
