### ISSUE TITLE
Impossibilidade de retorno de significados de palavras com grafia igual mas acentuação diferente.

### ISSUE THREAD

**Issue by FernandoGuiao** [ThiagoNelsi/dicio-api#19]
Olá Thiago! Interessante a ideia da API.

Percebi que não tem como retornar o significado de algumas palavras, de acordo com a acentuação.
Palavras como: 'coco, cocó, cocô e coço', 'metro e metrô'.

**Comment by ThiagoNelsi** [comment]
Olá, realmente, ótima observação! Irei estudar alguma forma de contornar esse problema. Fique a vontade para enviar um pull request caso encontre alguma solução.

**Comment by FernandoGuiao** [comment]
Fiz um Pull request. Ainda não resolve completamente, já que ainda não consigo retornar somente a palavra enviada. Mas podemos fazer um filtro dos resultados da rota nova, e manter a palavra inserida para comparação antes de mandar pro `sanitizeWords()`. O que acha?

Vai ficar mais lento a resposta, já que verifica todas as possibilidades da palavra. Consegue pensar em outra forma mais rápida?
