### ISSUE TITLE
Palavras com diferentes acentuações não podem ser retornadas ao usar allMeanings

### ISSUE THREAD

**Issue by enzon19** [ThiagoNelsi/dicio-api#25]
Palavras, como `vovô`, que possuem duas ou mais opções de acentuações não podem ser achadas. No caso de `vovô`, ao usar `allMeanings/vovo`, apenas vovó é retornado. Não sei se é culpa do próprio sistema do Dicio ou se é um problema especificamente desta palavra já que o mesmo problema não acontece com `avô`, `avó` e `avo`.

**Comment by ThiagoNelsi** [comment]
Obrigado pelo report, Enzo! A versão 2.0 da API deve ser lançada amanhã e irá trazer a correção para esse bug, estou trabalhando nos últimos detalhes. Na nova versão, a rota `/allMeanings` será removida e você poderá utilizar a rota padrão `/v2/vovô` para conseguir o resultado correto.

**Comment by ThiagoNelsi** [comment]
Nova versão no ar, erro corrigido! Obrigado mais uma vez por reportar @enzon19 😀

**Comment by enzon19** [comment]
Aaa eu que agradeço por responder e criar este projeto! Esse problema foi corrigido, mas o `allMeanings` resolvia um problema das palavras apenas acentuadas, como `feijão`. O Dicio não disponibiliza a versão `feijão`, apenas `feijao`, só que o `allMeanings` resolvia isto. Vou criar um outro issue só por motivos de organização e também não sei se será possível resolver isto nesse caso, mas o `allMeanings` conseguia.
