### ISSUE TITLE
Palavras que são apenas acentuadas não podem ser encontradas ao usar versão acentuada para obter dados

### ISSUE THREAD

**Issue by enzon19** [ThiagoNelsi/dicio-api#26]
Na v1, ao usar o allMeanings, resolvia um problema das palavras apenas acentuadas, como feijão. O Dicio não disponibiliza a versão feijão, apenas feijao, veja:
- [`v2/feij%C3%A3o`](https://significado.herokuapp.com/v2/feij%C3%A3o) — retorna um erro
- [`v2/feijao`](https://significado.herokuapp.com/v2/feijao) — retorna feijão
- [`allMeanings/feij%C3%A3o`](https://significado.herokuapp.com/allMeanings/feij%C3%A3o) — retorna feijão
- [dicio.com.br/feijao](https://dicio.com.br/feijao) — retorna feijão
- [dicio.com.br/feij%C3%A3o](https://dicio.com.br/feij%C3%A3o) — não encontra

Não sei se será possível corrigir isto, já que a culpa é do Dicio, mas como eu disse, com o `allMeanings` era corrigido

**Comment by ThiagoNelsi** [comment]
Valeu Enzo, encontrei uma solução e estou trabalhando na correção!
