### ISSUE TITLE
API Off

### ISSUE THREAD

**Issue by guiireal** [ThiagoNelsi/dicio-api#34]
![image](https://user-images.githubusercontent.com/13739343/205963768-5853a69c-3132-42e3-901d-b6a56f6f22a6.png)

**Comment by lvieira268** [comment]
Is this API still being maintained? Do you intend to reactivate the server?
is a good API

**Comment by guiireal** [comment]
> Is this API still being maintained? Do you intend to reactivate the server? is a good API


The owner of the repository didn't answer anymore, he tried to send a message, offering me to host the dictionary, but he didn't get any answers. :(

**Comment by ThiagoNelsi** [comment]
Hi, guys! Sorry for all this time I've been out.

The API was previously hosted in a Heroku free plan, which is no longer available. For this reason I changed the host to Vercel.

The new API endpoint is https://dicio-api-ten.vercel.app/
