### ISSUE TITLE
Consulta de api

### ISSUE THREAD

**Issue by nikoz84** [ThiagoNelsi/dicio-api#4]
Bom dia sou desenvolvedor do projeto http://pat.educacao.ba.gov.br, e estou querendo implementar uma sugestão de palavra quando não existir tags cadastrados em nosso banco, seu projeto que esta no heroku é permanente??

**Comment by ThiagoNelsi** [comment]
Olá bom dia, sinto muito pela demora, tive que ficar por fora do GitHub por um tempo, espero poder ajudar ainda.

A ideia é manter o projeto rodando no heroku sim! Contudo, tenha em mente que ele está hospedado em um plano gratuito do Heroku, pois não tenho como bancar os custos da hospedagem paga. Por conta disso a latência na comunicação pode ser alta fazendo com que a request demore para ser resolvida.
