### ISSUE TITLE
API fora do ar

### ISSUE THREAD

**Issue by PedroCestaro** [ThiagoNelsi/dicio-api#41]
Fala pessoal! Como vcs estão?

 Vinha utilizando a API aqui, e de repente parece que ela está fora do ar, no link: https://significado.herokuapp.com/

 Alguém sabe me dizer se ela está online em algum outro link?

 Abraços!

**Comment by ThiagoNelsi** [comment]
Boa noite!

O novo endpoint é https://dicio-api-ten.vercel.app/v2/
